### PR TITLE
bug fixed of Partial confirmation buttons showing for same datatype i…

### PR DESCRIPTION
**Pull request by Priyankakore21**
…n Add property functionality

### CODE REVIEW

**Comment by rahul-tarafdar-synerzip** [comment]
is this fix relevant now. i have pulled shashank's pr.

Check with latest new_editor branch if the issue you tried to solve got solved there by shanshank's pr. if yes then close this pr

**Comment by Priyankakore21** [comment]
No, it is not solved in shashank's pr. I have solved it.

**Comment by rahul-tarafdar-synerzip** [comment]
> No, it is not solved in shashank's pr. I have solved it.

ok. then lets fix up the conflicts

**Comment by rahul-tarafdar-synerzip** [comment]
also it has conflicts where shashank changed some code.
check with him if your changes are not regressing what he has fixed

**Comment by rahul-tarafdar-synerzip** [comment]
This PR has lots of unwanted code changes.
Get a fresh branch and do only required changes and raise a new PR.
Abandon this PR

**Comment by Priyankakore21** [comment]
ok

**Comment by Priyankakore21** [comment]
This PR has lots of unwanted code changes. So making a new branch for required changes

**Pull request closed without merging**
